---
version: '3'
services:
  votingapp:
    image: dockersamples/examplevotingapp_vote
    ports:
      -5050:80
    deploy:
      replicas: 2
  redis-app:
    image: redis
    ports:
      -6379:6379
  workerapp:
    image: dockersamples/examplevotingapp_worker
  postgresapp:
    image: postgres
    port:
      -5432:5432
    enviroment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: vinay
      POSTGRES_DB: mydb
  resultapp:
    image: dockersamples/examplevotingapp_result
    ports:
      -6060:80
    deploy:
      replicas: 2


