apiVersion: v1
kind: Service
metadata:
  name: resultsevices
  labels:
    name: result
    author: vinay
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 3070
  selector:
    name: resultapp
